apiVersion: v1
kind: Service
metadata:
  name: message-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: message-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-api
  template:
    metadata:
      labels:
        app: message-api
    spec:
      containers:
        - name: message-api
          image: sublayer/message-api:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: message-api-config
            - secretRef:
                name: message-api-secret
