apiVersion: v1
kind: Service
metadata:
  name: message-client
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: message-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-client
  template:
    metadata:
      labels:
        app: message-client
    spec:
      containers:
        - name: message-client
          image: sublayer/message-client:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: message-client-config
